export enum UserServiceSubject {
  FindByEmail = 'userServiceFindByEmail',
  FindById = 'userServiceFindById',
  FindByIdOnly = 'userServiceFindByIdOnly',
  FindByZaloIdAndTenantId = 'userServiceFindByZaloIdAndTenantId',
  Create = 'userServiceCreate',
  CreateZaloUser = 'userServiceCreateZaloUser',
  Update = 'userServiceUpdate',
  Delete = 'userServiceDelete',
  FindZaloUsersByTenantId = 'userServiceFindZaloUsersByTenantId',
  UpdateStatus = 'userServiceUpdateStatus',
  ConfirmByCode = 'userServiceConfirmByCode',
  IncrementFailedLoginAttempts = 'userServiceIncrementFailedLoginAttempts',
  ResetVerificationCode = 'userServiceResetVerificationCode',
  UpdateSocialProviders = 'userServiceUpdateSocialProviders',
  ValidateAgencyCanImpersonate = 'userServiceValidateAgencyCanImpersonate',
  ValidateOrganizationAdminCanImpersonate = 'userServiceValidateOrganizationAdminCanImpersonate',
  FindByIds = 'userServiceFindByIds',
}
