export enum ErrorCode {
  // Auth Service
  OPERATION_NOT_ALLOWED = 'OPERATION_NOT_ALLOWED',

  USER_NOT_FOUND = 'USER_NOT_FOUND',
  USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS',
  USER_ACCOUNT_INACTIVE = 'USER_ACCOUNT_INACTIVE',
  USER_ACCOUNT_SUSPENDED = 'USER_ACCOUNT_SUSPENDED',
  USER_ACCOUNT_PENDING = 'USER_ACCOUNT_PENDING',
  INVALID_USER_TYPE = 'INVALID_USER_TYPE',

  USER_IS_NOT_ADMIN_OF_TENANT = 'USER_IS_NOT_ADMIN_OF_TENANT',
  CREATE_USER_FAILED = 'CREATE_USER_FAILED',
  EMAIL_ALREADY_EXISTS = 'EMAIL_ALREADY_EXISTS',
  UPDATE_USER_EMAIL_NOT_ALLOWED = 'UPDATE_USER_EMAIL_NOT_ALLOWED',
  PASSWORD_RULES_MISMATCH = 'PASSWORD_RULES_MISMATCH', // pragma: allowlist secret

  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  INVALID_ZALO_ACCESS_TOKEN = 'INVALID_ZALO_ACCESS_TOKEN',
  INVALID_REFRESH_TOKEN = 'INVALID_REFRESH_TOKEN',
  INVALID_RESET_TOKEN = 'INVALID_RESET_TOKEN',
  RESET_TOKEN_EXPIRED = 'RESET_TOKEN_EXPIRED',
  INVALID_USER_STATUS = 'INVALID_USER_STATUS',
  INVALID_VERIFICATION_CODE = 'INVALID_VERIFICATION_CODE',
  VERIFICATION_TOKEN_EXPIRED = 'VERIFICATION_TOKEN_EXPIRED',
  INVALID_VERIFICATION_TOKEN = 'INVALID_VERIFICATION_TOKEN',
  GOOGLE_AUTHENTICATION_FAILED = 'GOOGLE_AUTHENTICATION_FAILED',

  PRODUCT_NOT_FOUND = 'PRODUCT_NOT_FOUND',
  PRODUCT_ALREADY_EXISTS = 'PRODUCT_ALREADY_EXISTS',
  INVALID_RATING = 'INVALID_RATING',

  INSUFFICIENT_STOCK = 'INSUFFICIENT_STOCK',
  STOCK_NOT_FOUND = 'STOCK_NOT_FOUND',
  STOCK_ALREADY_EXISTS = 'STOCK_ALREADY_EXISTS',

  CATEGORY_NOT_FOUND = 'CATEGORY_NOT_FOUND',
  INVALID_CATEGORY_PARENT = 'INVALID_CATEGORY_PARENT',
  CATEGORY_ALREADY_EXISTS = 'CATEGORY_ALREADY_EXISTS',

  BOOKING_NOT_FOUND = 'BOOKING_NOT_FOUND',
  SLOT_NOT_FOUND = 'SLOT_NOT_FOUND',
  SLOT_ALREADY_EXISTS = 'SLOT_ALREADY_EXISTS',

  ORDER_NOT_FOUND = 'ORDER_NOT_FOUND',
  ORDER_HISTORY_NOT_FOUND = 'ORDER_HISTORY_NOT_FOUND',

  CART_IS_EMPTY = 'CART_IS_EMPTY',

  CONTENT_NOT_FOUND = 'CONTENT_NOT_FOUND',

  TENANT_NOT_FOUND = 'TENANT_NOT_FOUND',
  ORGANIZATION_NOT_FOUND = 'ORGANIZATION_NOT_FOUND',
  GET_IN_APP_NOTIFICATIONS_FAILED = 'GET_IN_APP_NOTIFICATIONS_FAILED',
  USER_CHANNEL_ALREADY_EXISTS = 'USER_CHANNEL_ALREADY_EXISTS',
  CREATE_USER_CHANNEL_FAILED = 'CREATE_USER_CHANNEL_FAILED',
  USER_CHANNEL_NOT_FOUND = 'USER_CHANNEL_NOT_FOUND',
  SHIPPING_PROVIDER_NOT_FOUND = 'SHIPPING_PROVIDER_NOT_FOUND',
  SHIPPING_METHOD_NOT_FOUND = 'SHIPPING_METHOD_NOT_FOUND',
  SHIPPING_METHOD_NOT_AVAILABLE = 'SHIPPING_METHOD_NOT_AVAILABLE',
  SHIPPING_METHOD_IS_NOT_VALID = 'SHIPPING_METHOD_IS_NOT_VALID',

  CREATE_ORDER_FAILED = 'CREATE_ORDER_FAILED',
  VOUCHER_IS_INVALID = 'VOUCHER_IS_INVALID',
  ORDER_IS_NOT_NEW = 'ORDER_IS_NOT_NEW',
  VOUCHER_IS_NOT_ASSIGNED_TO_USER = 'VOUCHER_IS_NOT_ASSIGNED_TO_USER',
  NOT_APPLICABLE_FOR_THIS_VOUCHER = 'NOT_APPLICABLE_FOR_THIS_VOUCHER',
  MINIMUM_AMOUNT_NOT_MET = 'MINIMUM_AMOUNT_NOT_MET',
  VARIANT_IS_NOT_AVAILABLE = 'VARIANT_IS_NOT_AVAILABLE',
  MIXED_CURRENCIES_NOT_ALLOWED = 'MIXED_CURRENCIES_NOT_ALLOWED',

  // sdui
  LAYOUT_ALREADY_EXISTS = 'LAYOUT_ALREADY_EXISTS',
  NO_DEFAULT_ADDRESS = 'NO_DEFAULT_ADDRESS',
  ADDRESS_NOT_FOUND = 'ADDRESS_NOT_FOUND',

  // organization
  BRANCH_NOT_FOUND = 'BRANCH_NOT_FOUND',

  // event
  EVENT_NOT_FOUND = 'EVENT_NOT_FOUND',
  EVENT_REGISTRATION_FAILED = 'EVENT_REGISTRATION_FAILED',
  EVENT_REGISTRATION_NOT_FOUND = 'EVENT_REGISTRATION_NOT_FOUND',
  EVENT_ALREADY_CHECKED_IN = 'EVENT_ALREADY_CHECKED_IN',

  //checkin
  CHECKIN_NOT_FOUND = 'CHECKIN_NOT_FOUND',
  CHECKIN_FAILED = 'CHECKIN_FAILED',

  // clockin
  SHIFT_NOT_FOUND = 'SHIFT_NOT_FOUND',
  CLOCKIN_NOT_FOUND = 'CLOCKIN_NOT_FOUND',
  CLOCKIN_FAILED = 'CLOCKIN_FAILED',
  CLOCKIN_ALREADY_EXISTS = 'CLOCKIN_ALREADY_EXISTS',

  // subscription
  SUBSCRIPTION_PACKAGE_NOT_FOUND = 'SUBSCRIPTION_PACKAGE_NOT_FOUND',
  SUBSCRIPTION_ALREADY_EXISTS = 'SUBSCRIPTION_ALREADY_EXISTS',
  SUBSCRIPTION_IS_PENDING = 'SUBSCRIPTION_IS_PENDING',
  SUBSCRIPTION_NOT_FOUND = 'SUBSCRIPTION_NOT_FOUND',
  PACKAGE_PRICING_NOT_FOUND = 'PACKAGE_PRICING_NOT_FOUND',
  CREATE_USER_SUBSCRIPTION_FAILED = 'CREATE_USER_SUBSCRIPTION_FAILED',
  CREATE_SUBSCRIPTION_PACKAGE_FAILED = 'CREATE_SUBSCRIPTION_PACKAGE_FAILED',
  UPDATE_SUBSCRIPTION_PACKAGE_FAILED = 'UPDATE_SUBSCRIPTION_PACKAGE_FAILED',
  UPDATE_USER_SUBSCRIPTION_FAILED = 'UPDATE_USER_SUBSCRIPTION_FAILED',
  USER_HAS_USED_TRIAL = 'USER_HAS_USED_TRIAL',
  TRIAL_PACKAGE_MUST_HAVE_ONE_PRICING = 'TRIAL_PACKAGE_MUST_HAVE_ONE_PRICING',
  INVALID_UPGRADABLE_PACKAGES = 'INVALID_UPGRADABLE_PACKAGES',
  TRIAL_PACKAGE_MUST_HAVE_ONE_TIME_BILLING = 'TRIAL_PACKAGE_MUST_HAVE_ONE_TIME_BILLING',
  TRIAL_PACKAGE_MUST_HAVE_DAYS_DURATION_UNIT = 'TRIAL_PACKAGE_MUST_HAVE_DAYS_DURATION_UNIT',
  TRIAL_PACKAGE_MUST_HAVE_ZERO_AMOUNT = 'TRIAL_PACKAGE_MUST_HAVE_ZERO_AMOUNT',
  PAID_PACKAGE_MUST_HAVE_POSITIVE_AMOUNT = 'PAID_PACKAGE_MUST_HAVE_POSITIVE_AMOUNT',
  PAID_PACKAGE_MUST_HAVE_AT_LEAST_ONE_PRICING = 'PAID_PACKAGE_MUST_HAVE_AT_LEAST_ONE_PRICING',

  // payment
  PAYMENT_VENDOR_NOT_FOUND = 'PAYMENT_VENDOR_NOT_FOUND',
  CREATE_MOMO_PAYMENT_FAILED = 'CREATE_MOMO_PAYMENT_FAILED',
  CREATE_VNPAY_PAYMENT_FAILED = 'CREATE_VNPAY_PAYMENT_FAILED',
  PAYMENT_TRANSACTION_NOT_FOUND = 'PAYMENT_TRANSACTION_NOT_FOUND',
  PAYMENT_VENDOR_ALREADY_EXISTS = 'PAYMENT_VENDOR_ALREADY_EXISTS',
  PAYMENT_VENDOR_NOT_SUPPORTED = 'PAYMENT_VENDOR_NOT_SUPPORTED',

  CAMPAIGN_NOT_FOUND = 'CAMPAIGN_NOT_FOUND',
  CAMPAIGN_WITH_ID_NOT_FOUND = 'CAMPAIGN_WITH_ID_NOT_FOUND',
  CAMPAIGN_TRIGGER_WITH_ID_NOT_FOUND = 'CAMPAIGN_TRIGGER_WITH_ID_NOT_FOUND',
  CAMPAIGN_TRIGGERS_WITH_TENANT_ID_NOT_FOUND = 'CAMPAIGN_TRIGGERS_WITH_TENANT_ID_NOT_FOUND',
  VOUCHER_TYPE_ID_REQUIRED = 'VOUCHER_TYPE_ID_REQUIRED',
  DEFAULT_LOYALTY_PROGRAM_NOT_FOUND = 'DEFAULT_LOYALTY_PROGRAM_NOT_FOUND',
  LOYALTY_PROGRAM_NOT_FOUND = 'LOYALTY_PROGRAM_NOT_FOUND',
  ACTIVE_LOYALTY_PROGRAM_NOT_FOUND = 'ACTIVE_LOYALTY_PROGRAM_NOT_FOUND',
  DEFAULT_LOYALTY_TIER_NOT_FOUND = 'DEFAULT_LOYALTY_TIER_NOT_FOUND',
  LOYALTY_TIER_NOT_FOUND = 'LOYALTY_TIER_NOT_FOUND',
  NEXT_LOYALTY_TIER_NOT_FOUND = 'NEXT_LOYALTY_TIER_NOT_FOUND',
  NO_LOYALTY_TIERS_FOUND = 'NO_LOYALTY_TIERS_FOUND',
  POINT_BALANCE_CREATION_FAILED = 'POINT_BALANCE_CREATION_FAILED',
  MEMBERSHIP_NOT_FOUND = 'MEMBERSHIP_NOT_FOUND',
  POINT_BALANCE_PROFILE_NOT_FOUND = 'POINT_BALANCE_PROFILE_NOT_FOUND',
  POINT_BALANCE_PROFILE_ALREADY_EXISTS = 'POINT_BALANCE_PROFILE_ALREADY_EXISTS',
  POINT_EXPIRY_RULE_NOT_FOUND = 'POINT_EXPIRY_RULE_NOT_FOUND',
  VOUCHER_TYPE_NOT_AVAILABLE_FOR_REDEMPTION = 'VOUCHER_TYPE_NOT_AVAILABLE_FOR_REDEMPTION',
  INSUFFICIENT_POINTS = 'INSUFFICIENT_POINTS',
  USER_REDEMPTION_LIMIT_REACHED = 'USER_REDEMPTION_LIMIT_REACHED',
  TOTAL_REDEMPTION_LIMIT_REACHED = 'TOTAL_REDEMPTION_LIMIT_REACHED',
  VOUCHER_ISSUE_FAILED = 'VOUCHER_ISSUE_FAILED',
  VOUCHER_WITH_ID_NOT_FOUND = 'VOUCHER_WITH_ID_NOT_FOUND',
  VOUCHER_TYPE_NOT_FOUND = 'VOUCHER_TYPE_NOT_FOUND',
  VOUCHER_IS_NOT_ACTIVE = 'VOUCHER_IS_NOT_ACTIVE',
  VOUCHER_HAS_ALREADY_BEEN_REDEEMED = 'VOUCHER_HAS_ALREADY_BEEN_REDEEMED',
  VOUCHER_IS_NOT_YET_ACTIVE = 'VOUCHER_IS_NOT_YET_ACTIVE',
  VOUCHER_HAS_EXPIRED = 'VOUCHER_HAS_EXPIRED',
  USER_IDS_CANNOT_BE_EMPTY = 'USER_IDS_CANNOT_BE_EMPTY',
  MAXIMUM_10000_USERS_PER_BATCH = 'MAXIMUM_10000_USERS_PER_BATCH',
  BULK_VOUCHER_ISSUE_FAILED = 'BULK_VOUCHER_ISSUE_FAILED',

  // survey
  CREATE_SURVEY_FAILED = 'CREATE_SURVEY_FAILED',
  SURVEY_NOT_FOUND = 'SURVEY_NOT_FOUND',
  SURVEY_ALREADY_EXISTS = 'SURVEY_ALREADY_EXISTS',
  UPDATE_SURVEY_FAILED = 'UPDATE_SURVEY_FAILED',
  CREATE_USER_RESPONSE_FAILED = 'CREATE_USER_RESPONSE_FAILED',
  USER_NOT_AUTHORIZED_TO_RESPOND = 'USER_NOT_AUTHORIZED_TO_RESPOND',
  USER_RESPONSE_NOT_FOUND = 'USER_RESPONSE_NOT_FOUND',
  CREATE_FORM_FAILED = 'CREATE_FORM_FAILED',
  UPDATE_FORM_FAILED = 'UPDATE_FORM_FAILED',
  FORM_NOT_FOUND = 'FORM_NOT_FOUND',

  // notification
  IN_APP_NOTIFICATION_NOT_FOUND = 'IN_APP_NOTIFICATION_NOT_FOUND',
  UPDATE_IN_APP_NOTIFICATION_FAILED = 'UPDATE_IN_APP_NOTIFICATION_FAILED',
  CREATE_IN_APP_NOTIFICATION_FAILED = 'CREATE_IN_APP_NOTIFICATION_FAILED',
  CREATE_TEMPLATE_FAILED = 'CREATE_TEMPLATE_FAILED',
  TEMPLATE_NOT_FOUND = 'TEMPLATE_NOT_FOUND',
  UPDATE_TEMPLATE_FAILED = 'UPDATE_TEMPLATE_FAILED',
  TEMPLATE_ALREADY_EXISTS = 'TEMPLATE_ALREADY_EXISTS',

  // course
  USER_COLLECTION_NOT_FOUND = 'USER_COLLECTION_NOT_FOUND',
  UNABLE_TO_GET_WORDS_FROM_DICTIONARY = 'UNABLE_TO_GET_WORDS_FROM_DICTIONARY',
  UNABLE_TO_GET_SENTENCES = 'UNABLE_TO_GET_SENTENCES',
  USER_COLLECTIONS_LIMIT_REACHED = 'USER_COLLECTIONS_LIMIT_REACHED',
  ITEMS_PER_COLLECTION_LIMIT_REACHED = 'ITEMS_PER_COLLECTION_LIMIT_REACHED',
  UPLOAD_AUDIO_FAILED = 'UPLOAD_AUDIO_FAILED',
  UPLOAD_IMAGE_FAILED = 'UPLOAD_IMAGE_FAILED',
  LESSON_SPEAKING_NOT_FOUND = 'LESSON_SPEAKING_NOT_FOUND',
  WORD_NOT_BELONG_TO_LESSON_SPEAKING = 'WORD_NOT_BELONG_TO_LESSON_SPEAKING',
  SENTENCE_NOT_BELONG_TO_LESSON_SPEAKING = 'SENTENCE_NOT_BELONG_TO_LESSON_SPEAKING',

  // storage
  FILE_METADATA_NOT_FOUND = 'FILE_METADATA_NOT_FOUND',
  FILE_METADATA_CREATION_FAILED = 'FILE_METADATA_CREATION_FAILED',
  FILE_METADATA_UPDATE_FAILED = 'FILE_METADATA_UPDATE_FAILED',

  // rbac
  ROLE_NOT_FOUND = 'ROLE_NOT_FOUND',
  ROLE_ALREADY_EXISTS = 'ROLE_ALREADY_EXISTS',
  ROLE_IN_USE = 'ROLE_IN_USE',
  USER_ROLE_ALREADY_EXISTS = 'USER_ROLE_ALREADY_EXISTS',
  USER_ROLE_NOT_FOUND = 'USER_ROLE_NOT_FOUND',
  TENANT_ACCESS_DENIED = 'TENANT_ACCESS_DENIED',
  UNAUTHORIZED = 'UNAUTHORIZED',
}
