services:
  # ========================================
  # Microservices
  # ========================================
  zma-meeting:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dhte-zma-meeting
    restart: unless-stopped
    ports:
      - "3008:3008" # HTTP GraphQL
      - "4008:4008" # TCP Microservice
    env_file:
      - apps/zma-meeting/.env
    networks:
      - dhte-network
    command: ["dumb-init", "node", "dist/apps/zma-meeting/main.js"]
    # healthcheck:
  #   test: ["CMD", "curl", "-f", "http://localhost:3008/health"]
  #   interval: 30s
  #   timeout: 10s
  #   retries: 3
networks:
  dhte-streaming-network:
    external: true
