database:
  mongo:
    uri: mongodb://${username}:${password}@${host}/zma-user?directConnection=true&authSource=admin
kafka:
  service:
    brokers:
      - 89.233.105.251:9092
grpc:
  url: localhost:5001
  service:
    organization:
      url: localhost:5010
r2:
  imageAssetsBaseUrl: https://pub-1e38b9094c0e4453ae5cc43051dad9ff.r2.dev #pragma: allowlist secret
