export enum WSGateWayIncomingEvent {
  RequestJoin = 'request-join',
  Join = 'join',
  ApproveUser = 'approve-user',
  RejectUser = 'reject-user',
  GetPendingUsers = 'get-pending-users',
  Kick = 'kick',
  Leave = 'leave',
  GetRouterRtpCapabilities = 'get-router-rtp-capabilities',
  CreateTransport = 'create-transport',
  ConnectTransport = 'connect-transport',
  ConnectRecvTransport = 'connect-recv-transport',
  Produce = 'produce',
  Consume = 'consume',
  Transcript = 'transcript',
  StopTranscription = 'stop-transcription',
  StartRecording = 'start-recording',
  StopRecording = 'stop-recording',
  Ping = 'ping',
}

export enum WSGateWayOutgoingEvent {
  NewUser = 'new-user',
  YouAreAdmin = 'you-are-admin',
  UsersInRoom = 'users-in-room',
  NewProducer = 'new-producer',
  JoinError = 'join-error',
  WaitingApproval = 'waiting-approval',
  PendingUsers = 'pending-users',
  ApproveRequest = 'approve-request',
  ApprovedToJoin = 'approved-to-join',
  RejectedToJoin = 'rejected-to-join',
  Kicked = 'kicked',
  UserLeft = 'user-left',
  LogAnnouncedIp = 'log-announced-ip',
  ClearSubtitle = 'clear-subtitle',
  TranscriptEn = 'transcript-en',
  StopTranscript = 'stop-transcript',
}
